In [53]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor


ds=pd.read_csv('insurance-3.csv')
ds

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [54]:


ds.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [55]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [56]:
def smoker(smoke)->int:
    if smoke=='yes':
        return 1
    return 0
ds['smoker']=ds['smoker'].apply(smoker) 
ds

      age     sex     bmi  children  smoker     region      charges
0      19  female  27.900         0       1  southwest  16884.92400
1      18    male  33.770         1       0  southeast   1725.55230
2      28    male  33.000         3       0  southeast   4449.46200
3      33    male  22.705         0       0  northwest  21984.47061
4      32    male  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
1333   50    male  30.970         3       0  northwest  10600.54830
1334   18  female  31.920         0       0  northeast   2205.98080
1335   18  female  36.850         0       0  southeast   1629.83350
1336   21  female  25.800         0       0  southwest   2007.94500
1337   61  female  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [57]:

X=ds.drop(['charges'],axis=1)
y=ds['charges']
X,y

(      age     sex     bmi  children  smoker     region
 0      19  female  27.900         0       1  southwest
 1      18    male  33.770         1       0  southeast
 2      28    male  33.000         3       0  southeast
 3      33    male  22.705         0       0  northwest
 4      32    male  28.880         0       0  northwest
 ...   ...     ...     ...       ...     ...        ...
 1333   50    male  30.970         3       0  northwest
 1334   18  female  31.920         0       0  northeast
 1335   18  female  36.850         0       0  southeast
 1336   21  female  25.800         0       0  southwest
 1337   61  female  29.070         0       1  northwest

 [1338 rows x 6 columns],
 0       16884.92400
 1        1725.55230
 2        4449.46200
 3       21984.47061
 4        3866.85520
            ...
 1333    10600.54830
 1334     2205.98080
 1335     1629.83350
 1336     2007.94500
 1337    29141.36030
 Name: charges, Length: 1338, dtype: float64)

In [58]:
cat_data=['sex','region']
num_data=['age','bmi','children','smoker']
preprocesses=ColumnTransformer(transformers=[
    ('cat',OneHotEncoder(),cat_data),
    ('num','passthrough',num_data)
])
pipeline=Pipeline(steps=[
    ('preprocess',preprocesses),
    ('models',RandomForestRegressor(max_depth=10,
 min_samples_leaf=4,
 min_samples_split= 10,
 n_estimators=200))
])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33)
pipeline.fit(X_train,y_train)
pipeline.predict(X_test)

array([11626.50072027, 28602.36932346,  9966.34111684, 13737.12823695,
       39440.46979754,  2006.74859358,  9068.26954935,  2350.40487901,
        2222.7147427 , 19626.49492584, 11286.98778636,  5760.72199911,
        4813.41593812,  3243.56439753, 15365.8788555 ,  4013.18519957,
       35704.80436886, 11475.32684262, 43558.31442964, 15110.5020599 ,
        3454.19985217,  9790.80623393,  6381.34946193, 43793.82638638,
       13812.39676905, 11600.764314  , 15299.08163364, 44198.19760707,
        6671.06917238, 11997.9029369 , 10614.80370907, 11707.28166474,
        5897.05706407, 15695.64146042,  1834.90081853,  7934.36820713,
       19174.99701282, 16660.52266698, 19291.38531656,  5640.94601333,
        4872.01712494, 20236.889847  ,  7510.90916636,  4221.71119266,
       11626.58558121, 21155.02535844,  9890.9068942 , 12393.65552181,
       10025.25570509, 48923.12720327,  5373.84215963, 13153.46847711,
       18822.47583017,  7969.29409522,  3132.62057653, 12274.92933699,
        3197.28617748,  7165.1534925 , 10918.2152391 ,  1947.47850085,
       35620.26175046, 12801.99201504, 14013.74095559,  6828.24539036,
        4201.11179027,  7665.57682996, 46941.64543742,  3178.97669602,
        6165.92685136, 12247.41267144, 36445.27255592, 12641.1514986 ,
        9817.26893186, 43558.55166759,  7915.69197674,  9545.02896831,
        9730.56291115,  8500.44141537, 13483.18901569,  5988.66299532,
        8482.19578278, 13404.34716041,  9687.19918084, 16088.84932145,
       14799.06711679,  7078.27783083, 11988.88339942,  5278.91430263,
       45619.3347558 , 44035.17663315, 37831.16920483,  7035.86294372,
        9899.74429178, 26072.12897706,  9402.76609146,  4193.26419358,
        8658.47248815,  6492.86442779, 35035.83849523, 10817.71596291,
        6499.20970345,  6886.80846368, 16139.57336324, 12617.09865513,
        4659.8130677 ,  7242.90943451,  4130.51063563,  7230.02191253,
        9695.17236638, 24003.47391073,  6607.52893823,  6991.73365064,
        5968.42100544,  3240.14778916,  7929.66192179,  7818.22757688,
       19679.77278845, 18355.46618074, 41371.14246776,  3710.88284645,
       14623.8868303 ,  3197.28617748, 14839.49714898, 35711.24945873,
        4562.51957727,  7736.06034231, 14100.6014104 , 24412.81279632,
        3363.78880184, 43588.9230343 ,  4966.0809744 , 37487.7347348 ,
       14327.20656412,  4252.65123244, 14754.12720638,  9690.21669726,
        5116.26952508,  8002.7420498 , 17490.63087742,  6555.97397868,
       40712.87712606, 11723.19633444, 15176.69253463,  6297.6403526 ,
        4189.34867752,  4256.57856655,  7371.04624532,  7489.84068806,
        3551.6216709 , 12820.24537921,  5388.7676211 ,  6340.77683341,
        7122.74800135,  9791.20423632,  6569.53618247, 20670.64680546,
        6397.87538697,  7621.90676337, 10128.65589126,  8953.33115137,
       38933.90333691,  8491.74881935, 10586.10613239,  3307.41227889,
        7346.74323025,  9886.34102949, 35386.15167549,  6078.60882276,
       12310.08792823, 35813.35561818,  8032.11711613, 35394.28670668,
       44410.13465004, 47082.7408577 , 34997.96577062, 16611.43865049,
       12496.69226003,  3053.88878072, 10410.02517378, 38523.97166576,
        3183.39670826,  6034.76219123,  6308.03256009, 12384.28225599,
       43344.09757735,  2693.22741155, 12210.75976444, 42000.39803968,
       12838.4267475 , 10980.54756287,  2349.65268542,  2194.66598596,
       13464.90477922,  5311.90944794, 35519.66684742,  3121.32336157,
        6535.8257785 , 14545.16376094, 47372.0352893 ,  9848.24364103,
       13071.00036647,  7217.802229  ,  9147.78200843,  7807.9829304 ,
       23946.00427787,  6138.11138619,  1996.24057107, 37312.05337531,
       11288.15363103, 13039.78891075, 14944.79871974, 17450.83231821,
       12053.34419197, 12043.86350112,  9749.4087458 , 43638.91039224,
        7883.01971495, 12235.55579044,  9556.35356627,  9629.45591487,
        2196.61738008,  4488.9490271 ,  4145.25498729, 12455.58491055,
       11903.60963512, 18539.56337637, 16580.66375266,  9380.40309709,
        2008.04053952,  3351.10769336,  4521.56063831,  6364.0878034 ,
       10166.6763007 ,  8616.71537191,  5326.24812997,  2600.29318046,
        2406.52189484,  4653.46865363, 10632.5812288 , 11528.04412707,
       15149.14710181, 10740.76507824,  3629.58171577, 11650.02985042,
       35679.25344273,  8482.59718874, 16565.49367464, 20741.63440482,
       15254.13709643, 36072.06060344, 10098.12860086,  4611.64456547,
       11400.69831783, 12910.9563931 ,  9392.1464003 ,  2746.2832707 ,
        7673.78472298,  6919.01805378, 39169.4556159 ,  3586.80464144,
        1923.35185083,  6736.72656423, 12162.70816037,  5203.05722629,
        9521.72553516,  7668.8972808 , 12201.99340501,  4625.97562932,
       12486.68523779, 13758.15607091,  6677.22193783, 42425.2631862 ,
       12205.74516237, 12066.9653448 , 13590.76679604,  4781.58876734,
       16827.83356376, 29692.09616438,  9039.37129536, 14986.04166962,
        7404.70947493, 14095.47495542, 35018.11646999,  2618.49754067,
       16526.89748725, 39708.43089397,  3651.57126313,  7684.88217263,
       11981.46075981,  6435.20359768,  6775.09443204,  6854.56075593,
       11582.47399137, 10226.33259261, 28464.51805536, 11052.89785962,
        2638.5449146 , 14148.28838021, 11274.30719575,  4150.66726336,
        2016.25314739,  9540.56671325,  7208.4746803 , 17031.85030717,
       27778.01389243,  9930.38391241, 43280.02543834,  6402.69979134,
        3542.81569988, 14010.04051721, 10678.06512243,  5610.80221341,
       41844.0393993 , 46743.60202124, 11682.4614768 ,  6569.72645064,
       10839.20732577, 10281.52405107, 46922.15380391,  7748.21436958,
       13603.92860621,  3995.08211013, 20575.56157974,  4265.52801433,
       27328.14297217, 44905.85158012,  4429.73592414, 25392.11759104,
       20966.4617054 , 12670.56350547,  8471.67032942, 11297.68639705,
       12265.77453305, 41215.597019  ,  6519.45860178, 14492.93110084,
       11215.82579805,  5085.1979756 , 14942.70238033, 12108.12933255,
       14335.52853306, 15127.13463649, 11695.50813204, 10381.70514727,
       13991.50936165, 41509.85778589,  3655.63866479, 28116.88626895,
       10267.44311992, 12152.28787683,  4857.31678643, 12555.93816268,
       24649.99111712, 26996.14177677, 10280.97668927, 11428.69311968,
        8768.68043769, 12572.797484  ,  3232.71695543, 15229.52902618,
        8203.0603783 , 12509.26540889,  3837.6929851 , 15321.37424973,
       46082.13538248, 24276.35359758,  9416.93121573,  5426.65668301,
        9745.70456522,  6864.85680698,  7519.93588978,  5026.59788708,
       43913.07267427, 10699.48959925,  9693.41743347, 12378.6692021 ,
       11242.05762756,  9413.52384418, 13711.6017813 , 10322.75473855,
        4185.99104001,  8492.751613  ,  9063.58605679, 15016.91167086,
       13085.71312048, 37831.95824083,  3064.97529752, 12078.12457153,
       10837.42862583,  9883.19375174, 28841.36936317, 13892.95042054,
       10033.03948596, 39397.77631035,  8241.26673657,  4121.43190396,
        5809.46860099, 44620.24001578,  4438.56855108,  4462.79387006,
        9594.42700734,  4826.06345402,  8867.32910189,  7992.44300745,
       15249.13933514, 15876.61843097,  4885.49650158, 10619.12206803,
       16873.9093806 , 26157.057311  , 10215.36719478,  6089.138563  ,
        2646.54548754, 14264.01438292, 12913.20776585,  6179.2204531 ,
        7548.78719121,  7994.18843201,  6164.63482176,  3406.72699683,
        7983.89469068, 12432.97066842,  6135.01952475,  1975.21891337,
        3634.51354958,  9961.45443219, 21536.08489688, 12436.78015477,
        7228.0119098 ,  2098.11314005,  9120.14324529, 10198.52747514,
        9925.66626502,  5885.66932881, 10729.61892094,  8811.36660946,
        9978.35662456, 12485.39857801,  1633.13075831, 38376.56453281,
       19631.62795616, 17469.16447264])

In [59]:

#dumping model
import pickle
with open('model_pred.pkl','wb') as f:
    pickle.dump(pipeline,f)